[GA] add M8 and M6 integration tests (#309)
* This tests against an updated node with the rebranding incorporated. Hence, change 'SubstrateeRegistry' → `Teerex`.
* Add `skip-ra` flag to mutual-remote attestation procedure to be able to exchange keys with `SGX_MODE=SW`
* Add Some Error types to `enclave/rs3072`, which were used to debug.
* Supply `mrenclave` with mock_register_enclave extrinsic because the integration tests read the `mrenclave` from the registry.
* local-setup: Read config from file and minor improvements.
* Closes #302
* Closes #250

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -9,6 +9,10 @@ on:
 
 env:
   CARGO_TERM_COLOR: always
+  WORKER_BIN: substratee-worker
+  CLIENT_BIN: substratee-client
+  ENCLAVE_BIN: enclave.signed.so
+  LOG_DIR: log
 
 jobs:
   build-test:
@@ -29,12 +33,31 @@ jobs:
           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
       - name: Build
         run:  SGX_MODE=SW make
-      - name: Worker & Client
+      - name: Test Worker & Client
         run: cargo test
       - name: Test Enclave # cargo test is not supported, see: https://github.com/apache/incubator-teaclave-sgx-sdk/issues/232
         run: |
           cd bin
           ./substratee-worker test -u
+
+      # Todo: #REBRAND path names
+      - name: Upload worker
+        uses: actions/upload-artifact@v2
+        with:
+          name: integritee-worker-${{ github.sha }}
+          path: bin/${{ env.WORKER_BIN }}
+
+      - name: Upload client
+        uses: actions/upload-artifact@v2
+        with:
+          name: integritee-client-${{ github.sha }}
+          path: bin/${{ env.CLIENT_BIN }}
+
+      - name: Upload enclave
+        uses: actions/upload-artifact@v2
+        with:
+          name: enclave-signed-${{ github.sha }}
+          path: bin/${{ env.ENCLAVE_BIN }}
 
   clippy:
     runs-on: ubuntu-latest
@@ -58,3 +81,135 @@ jobs:
         run: cargo clippy -- -D warnings
       - name: Enclave # Enclave is separate as it's not in the workspace
         run: cd enclave && cargo clippy -- -D warnings
+
+  integration-tests:
+    runs-on: ubuntu-latest
+    needs: build-test
+    container: "scssubstratee/substratee_dev:1804-2.12-1.1.3-001"
+    strategy:
+      fail-fast: false
+      matrix:
+        test: [M6, M8]
+        include:
+          - test: M6
+            demo_name: m6_demo_shielding_unshielding
+            demo_script: m6.sh
+          - test: M8
+            demo_name: m8_demo_direct_call
+            demo_script: m8.sh
+
+    env:
+      BIN_DIR: bin
+    steps:
+      - uses: actions/checkout@v2
+
+      # we can't use the `actions/setup-python@v2` due to cross compiling issues with
+      # ubuntu 18.04 and python > 3.6, but we need >3.6 for our scripts.
+      - name: Set up Python
+        run: |
+          sudo apt install software-properties-common -y
+          sudo add-apt-repository ppa:deadsnakes/ppa -y
+          sudo apt install python3.7 -y
+          python3.7 --version
+      - name: Download Worker
+        uses: actions/download-artifact@v2
+        with:
+          name: integritee-worker-${{ github.sha }}
+          path: ${{ env.BIN_DIR }}
+
+      - name: Download Client
+        uses: actions/download-artifact@v2
+        with:
+          name: integritee-client-${{ github.sha }}
+          path: ${{ env.BIN_DIR }}
+
+      - name: Download Enclave
+        uses: actions/download-artifact@v2
+        with:
+          name: enclave-signed-${{ github.sha }}
+          path: ${{ env.BIN_DIR }}
+
+        # If you want to debug ci and you don't want to build the binaries, you can replace the downloads above with
+        # the actions below to download binaries from an earlier run.
+#      - name: Download Worker
+#        uses: dawidd6/action-download-artifact@v2
+#        with:
+#          github_token: ${{secrets.GITHUB_TOKEN}}
+#          workflow: build_and_test.yml
+#          run_id: 1033249727
+#          name: integritee-worker-da8d4b442d3f2b09dbafb097d4d7a1bce409d518
+#          path: ${{ env.BIN_DIR }}
+#
+#      - name: Download Client
+#        uses: dawidd6/action-download-artifact@v2
+#        with:
+#          github_token: ${{secrets.GITHUB_TOKEN}}
+#          workflow: build_and_test.yml
+#          run_id: 1033249727
+#          name: integritee-client-da8d4b442d3f2b09dbafb097d4d7a1bce409d518
+#          path: ${{ env.BIN_DIR }}
+#
+#      - name: Download Enclave
+#        uses: dawidd6/action-download-artifact@v2
+#        with:
+#          github_token: ${{secrets.GITHUB_TOKEN}}
+#          workflow: build_and_test.yml
+#          run_id: 1033249727
+#          name: enclave-signed-da8d4b442d3f2b09dbafb097d4d7a1bce409d518
+#          path: ${{ env.BIN_DIR }}
+
+      - name: Download integritee-node
+        uses: dawidd6/action-download-artifact@v2
+        with:
+          github_token: ${{secrets.GITHUB_TOKEN}}
+          workflow: build.yml
+          # Todo: Change branch to master once merged
+          name: integritee-node-skip-ias-check
+          # in fact this action should download the latest artifact, but sometimes fails. Then we need to
+          # set the `run_id` to force a download of an updated binary.
+          run_id: 1033090291
+          path: node
+          repo: integritee-network/integritee-node
+
+      - name: Prepare working directory
+        run: |
+          mkdir -p ${{ env.LOG_DIR}}
+          chmod +x node/integritee-node
+          cd ${{ env.BIN_DIR }}
+          chmod +x ${{ env.WORKER_BIN }}
+          chmod +x ${{ env.CLIENT_BIN }}
+          chmod +x ${{ env.ENCLAVE_BIN }}
+
+      - name: "Setup Keys"
+        env:
+          KEY: ${{ secrets.IAS_PRIMARY_KEY }}
+          SPID: ${{ secrets.IAS_SPID }}
+        run: |
+          cd ${{ env.BIN_DIR }}
+          echo "${{ env.KEY }}" > key.txt
+          echo "$$ {{ env.SPID }}" > spid.txt
+
+      - name: Run local setup
+        # * `set -eo pipefail` is needed to return an error even if piped to `tee`.
+        shell: bash --noprofile --norc -eo pipefail {0}
+        run: |
+          touch ${{ env.LOG_DIR}}/local-setup.log
+          ./local-setup/launch.py local-setup/github-action-config.json 2>&1 | tee ${{ env.LOG_DIR}}/local-setup.log &
+          sleep 30
+
+      - name: ${{ matrix.demo_name }}
+        # * the change the symbolic link which points to the target/release... folder.
+        # * need overwrite default shell to bash to get access to the `source` cmd.
+        shell: bash --noprofile --norc -eo pipefail {0}
+        run: |
+          cd client
+          ln -sf ../${{ env.BIN_DIR }}/${{ env.CLIENT_BIN }} substratee-client
+          cd ..
+          source ./scripts/init_env.sh && ./scripts/${{ matrix.demo_script }}
+
+      - name: Upload logs
+        if: always()
+        uses: actions/upload-artifact@v2
+        with:
+          name: logs
+          path: ${{ env.LOG_DIR }}
